import asyncio
import gbapi

async def main():
	g = gbapi.Client()
	blog = await g.get_blog(19009)
	print(blog.name)
	await asyncio.sleep(1)
	castawat = await g.get_castaway(2246)
	print(castawat.name)
	await asyncio.sleep(1)
	concept = await g.get_concept(665)
	print(concept.name)
	await asyncio.sleep(1)
	effect = await g.get_effect(6491)
	print(effect.name)
	await asyncio.sleep(1)
	gamefile = await g.get_gamefile(11997)
	print(gamefile.name)
	await asyncio.sleep(1)
	gui = await g.get_gui(35313)
	print(gui.name)
	await asyncio.sleep(1)
	map = await g.get_map(210265)
	print(map.name)
	await asyncio.sleep(1)
	prefab = await g.get_prefab(7612)
	print(prefab.name)
	await asyncio.sleep(1)
	project = await g.get_project(35562)
	print(project.name)
	await asyncio.sleep(1)
	question = await g.get_question(3024)
	print(question.name)
	await asyncio.sleep(1)
	request = await g.get_request(13038)
	print(request.name)
	await asyncio.sleep(1)
	script = await g.get_script(10638)
	print(script.name)
	await asyncio.sleep(1)
	skin = await g.get_skin(178235)
	print(skin.name)
	await asyncio.sleep(1)
	sound = await g.get_sound(47719)
	print(sound.name)
	await asyncio.sleep(1)
	spray = await g.get_spray(77115)
	print(spray.name)
	await asyncio.sleep(1)
	texture = await g.get_texture(5969)
	print(texture.name)
	await asyncio.sleep(1)
	thread = await g.get_thread(217986)
	print(thread.name)
	await asyncio.sleep(1)
	tool = await g.get_tool(6773)
	print(tool.name)
	await asyncio.sleep(1)
	tutorial = await g.get_tutorial(13380)
	print(tutorial.name)
	await asyncio.sleep(1)
	ware = await g.get_ware(216)
	print(ware.name)
	await asyncio.sleep(1)
	wip = await g.get_wip(51620)
	print(wip.name)
	await g.close()

if __name__ == '__main__':
	l = asyncio.get_event_loop()
	l.run_until_complete(main())